### ISSUE TITLE
Crawler: pattern URL: allow use of wildcard in hostnames

### ISSUE THREAD

**Issue by AlexandreToyer** [jaeksoft/opensearchserver#14]
In the definition of URL patterns it should be possible to use a wildcard (`*`) also for the hostname part of the URL.

For instance: `http://*.mydomain.com/*`

Thank you,
Alexandre

**Comment by micktion** [comment]
I'm using OSS 1.5.12.  

I don't think this is working.  Whilst I can get results entering the full URL.  Attempting to use a wild card like...

file:/D:/*

... fails to return any results.  I've tested with both Query and Term filters.  Perhaps the issue is specific to indexes created with the file crawler.
