### ISSUE TITLE
Using OCR problem

### ISSUE THREAD

**Issue by Ansaldos** [jaeksoft/opensearchserver#1805]
Dear OpenSearchServer!

I have a problem with using OCR.
I installed Tesseract.

tesseract -v :

```
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.4.2) : libpng 1.6.21 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0
```

I can use with manually, so its work.
My setup in Runtime/Advanced page:

Enable OCR Checked
Path: /usr/bin/tesseract
HOCR file extension: hocr
Langauge: Hungarian (I installed the HUN package)

Environment variables:

```
export TESSDATA_PREFIX=/usr/local/share/tesseract-ocr
export TESS_PATH=$TESS_PATH:/usr/local/bin
export TESS_LD_LIBRARY_PATH=$TESS_LD_LIBRARY_PATH:/usr/local/lib
```

When i click on Check button, i got the following message:
	
`com.jaeksoft.searchlib.SearchLibException: com.jaeksoft.searchlib.util.ExecuteUtils$ExecutionException: Wrong exit value: 0`

Can u help me? I really want to use OCR (for scanned images) for indexing.

**Comment by emmanuel-keller** [comment]
I investigate your issue.

Currently we execute tesseract externally. We think about using the JNA integration provided by tess4j. This should improve the error feedback.
http://tess4j.sourceforge.net/

**Comment by Ansaldos** [comment]
Using Tesseract 3.03 version solved the problem.

**Comment by RimacV** [comment]
I had the same problem and observed the following. Maybe this is helpful for others passing by.

I partially followed the official tesseract build [guidelines](https://github.com/tesseract-ocr/tesseract/wiki/Compiling) and installed the packages below. Note that these packages are not mentioned in the[ opensearchserver instructions](http://www.opensearchserver.com/documentation/faq/installation/how_to_install_Tesseract-3_on_Debian.md)


```
sudo apt-get install g++ # or clang++ (presumably)
sudo apt-get install autoconf automake libtool
sudo apt-get install pkg-config
sudo apt-get install libpng-dev
sudo apt-get install libjpeg8-dev
sudo apt-get install libtiff5-dev
sudo apt-get install zlib1g-dev

```
After building tesseract succesfully,
tesseract -v showed the following output
```
tesseract 3.02.02
 leptonica-1.69
  libjpeg 8d : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11

```

It seems that opensearchserver cannot handle a leptonica version which was build with one of these (or maybe all, I did not check)

``` libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11```

I removed all of these packages with 
```
sudo apt-get remove libpng-dev
sudo apt-get remove libjpeg8-dev
sudo apt-get remove libtiff5-dev
sudo apt-get remove zlib1g-dev
```
For some reason I could not remove ```libjpeg8-dev``` (Was not found by apt-get remove)
Anyway I rebuilded leptonica and now typing tesseract -v shows the following output

```
tesseract 3.02.02
 leptonica-1.69
  libjpeg 8d : 

```
Now with this version of tesseract opensearchserver works correctly.
That's why I think it  has nothing to do with the tesseract version 3.02 or tesseract 3.03. I think the problem is caused by leptonica.
